name: Android kernel build test
on:
  push:
    branches:
      - master

jobs:
  TestBuild:
    runs-on: ubuntu-latest
    steps:
      - name: ↗️ Checkout
        uses: actions/checkout@v2
      - name: ⚙️ setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential binutils-aarch64-linux-gnu ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses5 lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev
      - name: 🔨 Setup toolchain
        run: |
          mkdir -p ~/toolchain
          bash resolv_toolchain_linux.sh
      - name: 🏗️ Build Kernel
        run: |
          ./cleanup
          sudo bash build.sh
